resolver: nightly-2021-09-18
system-ghc: true
allow-different-user: true
packages:
  - bitfinex-client
  - reckless-trading-bot
extra-deps:
  - github: 21it/persistent-migration
    commit: 8d5d50204eec2d3d4bd9bb1f61e79ece2035ff8c
  - github: 21it/witch
    commit: 74bcf76cc968415e76d6804383a3ec22383459a5
