#!/bin/sh

export RECKLESS_TRADING_BOT_ENV="
{
  \"bfx\":{
    \"api_key\":\"$BITFINEX_API_KEY\",
    \"prv_key\":\"$BITFINEX_PRV_KEY\"
  },
  \"tele\":\"$TELEGRAM_BOT_KEY\",
  \"pairs\":{
    \"ADABTC\":{
      \"currency_kind\":\"Crypto\",
      \"max_quote_investment\":\"0.04\",
      \"min_profit_per_order\":\"0.001\",
      \"mode\":\"ObserveOnly\"
    },
    \"XMRBTC\":{
      \"currency_kind\":\"Crypto\",
      \"max_quote_investment\":\"0.01\",
      \"min_profit_per_order\":\"0.001\",
      \"mode\":\"ObserveOnly\"
    }
  },
  \"price_ttl\":300,
  \"order_ttl\":3600,
  \"report_start_amt\":\"0.029\",
  \"report_currency\":\"BTC\",
  \"libpq_conn_str\":\"postgresql://$USER@localhost/reckless-trading-bot\",
  \"log_env\":\"21it\",
  \"log_format\":\"Bracket\",
  \"log_severity\":\"info\",
  \"log_verbosity\":\"V3\"
}
"
