name: release
on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-nix-v0
        path: ./nix.tar.gz
    - name: Restore cache
      run: |
        docker run --rm \
          -v nix-$USER:/nix \
          -v $(pwd):/app \
          -w /app nixos/nix:2.3.12 \
          sh -c "tar -xvzf ./nix.tar.gz -C /" \
        || true
    - name: Release all
      run: ./nix/release-github.sh
    - name: Save cache
      run: |
        docker run --rm \
          -v nix-$USER:/nix \
          -v $(pwd):/app \
          -w /app nixos/nix:2.3.12 \
          sh -c "tar -czvf ./nix.tar.gz /nix/*"
    - name: Create github release
      if: github.ref_type == 'tag'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
    - name: Upload docker image
      if: github.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/docker-image-reckless-trading-bot.tar.gz
        asset_name: docker-image-reckless-trading-bot.tar.gz
        asset_content_type: application/gzip
    - name: Upload swarm file
      if: github.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/docker-compose.21it.yml
        asset_name: docker-compose.21it.yml
        asset_content_type: application/yaml
    - name: Docker registry login
      if: github.ref_type == 'tag'
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker registry push
      if: github.ref_type == 'tag'
      run: ./nix/github-package-push.sh ${{ github.ref_name }}
