name: release
on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-docker-volumes
        path: /var/lib/docker/volumes
    - name: release
      run: ./nix/release-github.sh
      continue-on-error: true
