name: release
on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-nix
        path: ./nix.tar.gz
    - name: Restore cache
      run: |
        docker run --rm \
          -v nix-$USER:/nix \
          -v $(pwd):/app \
          -w /app nixos/nix:2.3.12 \
          sh -c "tar -xvzf ./nix.tar.gz -C /" \
        || true
    - name: Release all
      run: |
        ./nix/release-github.sh \
        || true
    - name: Save cache
      run: |
        docker run --rm \
          -v nix-$USER:/nix \
          -v $(pwd):/app \
          -w /app nixos/nix:2.3.12 \
          sh -c "tar -czvf ./nix.tar.gz /nix/*"
